### ISSUE TITLE
Where else can PID file be written?

### ISSUE THREAD

**Issue by migurski** [openaddresses/pelias-api-ubuntu-xenial#1]
When running from `/usr/lib`, it’s not possible to create a pids directory. Can Pelias API be configured to write these to `/var`? /cc @orangejulius.

```
Error: EACCES: permission denied, mkdir '/usr/lib/nodejs/pelias-api/pids'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.exports.ensureDir (/usr/lib/nodejs/pelias-api/node_modules/cluster2/lib/misc.js:39:12)
    at HTTPServer.<anonymous> (/usr/lib/nodejs/pelias-api/node_modules/cluster2/lib/process.js:389:18)
    at HTTPServer.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at HTTPServer.emit (events.js:166:7)
    at emitListeningNT (net.js:1263:10)
    at nextTickCallbackWith1Arg (node.js:430:9)
    at process._tickCallback (node.js:352:17)
```

**Comment by migurski** [comment]
Looks like `pids` directory can be [configured in Cluster2 options](https://github.com/ql-io/cluster2/blob/master/README.md#options), at [line 9 of index.js](https://github.com/pelias/api/blob/2d136f75e/index.js#L9).

**Comment by migurski** [comment]
I’ve tried configuring `pids`, and it doesn’t seem to be enough. Cluster2 from https://github.com/missinglink/cluster2 as we’re using it is full of `process.cwd() + '/pids'`, which incorrectly tries to create directories in `/usr/lib/nodejs/pelias-api`.

**Comment by migurski** [comment]
The patch approach seems to work fine, no need to fix upstream for now.
